### ISSUE TITLE
qmail package name creates conflict with default ubuntu package

### ISSUE THREAD

**Issue by ismailyenigul** [rbuterbaugh/ubuntu-netqmail#3]
Ubuntu default package name is also qmail and it creates conflict. I have to check the version whenever install qmail on Ubuntu.
I think it is better to call your package as netqmail :)

Thanks

**Comment by rbuterbaugh** [comment]
My thought here was that this is intended to be a bugfix version in line with the main qmail package, but because it's not fundamentally a different package, I wanted to keep the name the same (and pin the version if necessary). Open to other perspectives though!
